from building import *
import rtconfig
cwd     = GetCurrentDir()
src = Glob('CMSIS/DeviceSupport/*.c')
CPPPATH = [cwd + '/CMSIS/CoreSupport', cwd + '/CMSIS/DeviceSupport', cwd + '/SWM181_StdPeriph_Driver']

src += Glob('SWM181_StdPeriph_Driver/*.c')

if rtconfig.PLATFORM in ['gcc']:
    src += ['CMSIS/DeviceSupport/startup/gcc/startup_SWM181.s']
elif rtconfig.PLATFORM in ['armcc', 'armclang']:
    src += ['CMSIS/DeviceSupport/startup/arm/startup_SWM181.s']
elif rtconfig.PLATFORM in ['iccarm']:
    src += ['CMSIS/DeviceSupport/startup/iar/startup_SWM181.s']
group = DefineGroup('Libraries', src, depend = [''], CPPPATH = CPPPATH)

Return('group')
