from building import *

cwd     = GetCurrentDir()
CPPPATH = [cwd]
src     = Split('''
                board.c
                ''')

if GetDepend(['RT_USING_SERIAL']):
    src += ['drv_uart.c']

if GetDepend(['RT_USING_PIN']):
    src += ['drv_gpio.c']

if GetDepend('BSP_USING_ADC'):
    src += ['drv_adc.c']

if GetDepend('BSP_USING_I2C0') or GetDepend('BSP_USING_I2C1'):
    src += ['drv_i2c.c']

if GetDepend('BSP_USING_PWM0') or GetDepend('BSP_USING_PWM1') or \
   GetDepend('BSP_USING_PWM2') or GetDepend('BSP_USING_PWM3'):
    src += ['drv_pwm.c']

if GetDepend('BSP_USING_RTC'):
    src += ['drv_rtc.c']

if GetDepend('BSP_USING_SPI0') or GetDepend('BSP_USING_SPI1'):
    src += ['drv_spi.c']

if GetDepend('BSP_USING_WDT'):
    src += ['drv_wdt.c']

if GetDepend('BSP_USING_CAN'):
    src += ['drv_can.c']

group = DefineGroup('Drivers', src, depend = [''], CPPPATH = CPPPATH)

Return('group')
